stages:
  download_data:
    cmd: python src/download_data.py
    deps:
    - src/download_data.py
    outs:
    - data/raw/MNIST
    - data/raw/caltech101
    - data/raw/cifar-10-batches-py
    - data/raw/cifar-10-python.tar.gz
    - data/raw/oxford-iiit-pet
  model_training:
    cmd: python src/model_training.py
    deps:
    - src/model_training.py
    - src/utils/models/training.py
    - src/utils/dvc/params.py
    - data/raw
    outs:
    - models/mnist_model.pt
    - models/cifar10_model.pt
    - models/oxford_iit_pet_model.pt
