stages:
  download_data:
    cmd: python src/download_data.py
    deps:
    - src/download_data.py
    outs:
    - data/raw/MNIST
    - data/raw/caltech101
    - data/raw/cifar-10-batches-py
    - data/raw/cifar-10-python.tar.gz
    - data/raw/oxford-iiit-pet